[profile.default]
src = "src"
out = "out"
libs = ['node_modules', 'lib']
remappings = [
    '@chainlink/contracts/=node_modules/@chainlink/contracts',
    '@chainlink/contracts-ccip/=node_modules/@chainlink/contracts-ccip',
    '@chainlink/local=node_modules/@chainlink/local',
]
solc = '0.8.20'


[rpc_endpoints]
base_sepolia = "https://public.stackup.sh/api/v1/node/base-sepolia"
